name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build Docker images with Docker Compose
      run: docker-compose up
      env:
        DB_ROOT_PASSWD: testpasswd
        DATABASE: workout_planner
        PORT_BACKEND: 8080
        PORT_FRONTEND: 3000
        ENABLE_CORS: true
        CLIENT_HOST: http://localhost:3000
        COOKIE_SECRET: somesecret
        DATABASE_URL: mysql://root:testpasswd@db:3306/workout_planner
  
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Run frontend tests
        run: docker exec -it workout-planner-frontend npm run cypress:run
